name: CI

on: push

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
      env:
        PIP_PROGRESS_BAR: off

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

    - name: Test
      run: python -m unittest -v --locals --buffer

    - name: Run
      run: ./mindpq.py > /dev/null && echo $?
